services:
#  postgres:
#    image: postgres:16-alpine
#    restart: unless-stopped
#    ports:
#      - "${POSTGRES_PORT:-5432}:5432"
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-hushdb}
#      POSTGRES_USER: ${POSTGRES_USER:-hushuser}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hushpassword}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - my-network
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-hushuser} -d ${POSTGRES_DB:-hushdb}"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --notify-keyspace-events KEA --protected-mode no
  backend:
#    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    networks:
      - my-network
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
#      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-hushdb}
#      DB_USERNAME: ${POSTGRES_USER:-hushuser}
#      DB_PASSWORD: ${POSTGRES_PASSWORD:-hushpassword}
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID:-test}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET:-test}
    depends_on:
#      postgres:
#        condition: service_healthy
      redis:
        condition: service_healthy
#
#volumes:
#  postgres_data:

networks:
  my-network:
    driver: bridge

