services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    networks:
      - my-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: narottam
      POSTGRES_PASSWORD: narottam
      POSTGRES_DB: narottam
    ports:
      - 5432:5432
    networks:
      - my-network

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data: